const qs=(s,p=document)=>p.querySelector(s);const qsa=(s,p=document)=>[...p.querySelectorAll(s)];
function bytes(n){if(!Number.isFinite(n))return '—';const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return `${n.toFixed(i?1:0)} ${u[i]}`}
function setStatus(message,error=false){const el=qs('#status');if(!el)return;el.textContent=message;el.classList.toggle('error',error);el.hidden=false}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
function stem(name){return name.replace(/\.[^.]+$/,'')}
function setupDropzone(inputId,onFiles){const input=qs(`#${inputId}`),zone=input?.closest('.dropzone');if(!input||!zone)return;input.addEventListener('change',()=>onFiles([...input.files]));['dragenter','dragover'].forEach(e=>zone.addEventListener(e,x=>{x.preventDefault();zone.classList.add('drag')}));['dragleave','drop'].forEach(e=>zone.addEventListener(e,x=>{x.preventDefault();zone.classList.remove('drag')}));zone.addEventListener('drop',e=>onFiles([...e.dataTransfer.files]))}
function loadImage(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('This image could not be opened.'))};img.src=url})}
function canvasBlob(canvas,type,quality){return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('This format is not supported by your browser.')),type,quality))}
function drawToCanvas(img,maxWidth,maxHeight,bg='transparent'){const ratio=Math.min(1,maxWidth/img.naturalWidth,maxHeight/img.naturalHeight),w=Math.max(1,Math.round(img.naturalWidth*ratio)),h=Math.max(1,Math.round(img.naturalHeight*ratio)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{alpha:bg==='transparent'});if(bg!=='transparent'){ctx.fillStyle=bg;ctx.fillRect(0,0,w,h)}ctx.drawImage(img,0,0,w,h);return canvas}
